import com.vanniktech.maven.publish.*

plugins {
    id 'java-library'
    id 'jacoco'
    id 'com.vanniktech.maven.publish' version '0.37.0' // publish to Maven Central
    id 'com.github.ben-manes.versions' version '0.65.0' // check for out-of-date dependencies (run 'dependencyUpdates' manually)
    id 'com.github.spotbugs' version '6.5.12' // spotbugs code analysis
}

group = 'com.imsweb'
version = file('VERSION').text.trim()
description = 'NAACCR API Client.'

println "Starting build using JDK ${Runtime.version().feature()}"

repositories {
    mavenCentral()

    maven {
        url = 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

dependencies {
	api 'com.squareup.retrofit2:retrofit:3.0.0'
    api 'com.squareup.retrofit2:converter-jackson:3.0.0'

    // retrofit will not update these dependencies to fix vulnerabilities
    api 'com.squareup.okhttp3:okhttp:5.5.0'
    api 'com.squareup.okio:okio:3.18.2'

    // newer version of dependency to fix vulnerability until converter-jackson is updated
    api 'com.fasterxml.jackson.core:jackson-databind:2.22.3'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.imsweb:seerutils:5.7'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-Xlint:unchecked' << '-Xlint:deprecation'
}

tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:none', '-quiet')
    options.addStringOption('encoding', 'UTF-8')
    options.addStringOption('charSet', 'UTF-8')
    options.addBooleanOption('html5', true)
}

jar {
    manifest {
        attributes('Implementation-Title': project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor': 'Information Management Services Inc.',
                'Created-By': System.properties['java.vm.version'] + ' (' + System.properties['java.vm.vendor'] + ')',
                'Built-By': System.getProperty('user.name'),
                'Built-Date': new Date(),
                'Built-JDK': System.getProperty('java.version'),
                'Automatic-Module-Name': 'com.imsweb.naaccr.api.client'
        )
    }
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}
test.finalizedBy jacocoTestReport

spotbugs {
    ignoreFailures = true
    excludeFilter.set(file('config/spotbugs/spotbugs-exclude.xml'))
}

def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
    def regex = /^[0-9,.v-]+(-r)?$/
    return !stableKeyword && !(version ==~ regex)
}

// https://github.com/ben-manes/gradle-versions-plugin
tasks.named("dependencyUpdates").configure {
    rejectVersionIf {
        isNonStable(it.candidate.version)
    }
}

// needed to deploy to Maven Central Portal
mavenPublishing {
    configure(new JavaLibrary(new JavadocJar.Javadoc(), new SourcesJar.Sources()))

    publishToMavenCentral(true)
    signAllPublications()

    pom {
        name = 'NAACCR API Client'
        description = 'Wraps calls to the NAACCR API.'
        url = 'https://github.com/imsweb/naaccr-api-client'
        inceptionYear = '2023'

        licenses {
            license {
                name = 'A modified BSD License (BSD)'
                url = 'https://github.com/imsweb/layout/blob/master/LICENSE'
                distribution = 'repo'
            }
        }

        developers {
            developer {
                id = 'depryf'
                name = 'Fabian Depry'
                email = 'depryf@imsweb.com'
            }
        }

        scm {
            url = 'https://github.com/imsweb/naaccr-api-client'
            connection = 'scm:https://github.com/imsweb/naaccr-api-client.git'
            developerConnection = 'scm:git@github.com:imsweb/naaccr-api-client.git'
        }
    }
}

// Gradle wrapper, this allows to build the project without having to install Gradle!
wrapper {
    gradleVersion = '9.8.1'
    distributionType = Wrapper.DistributionType.ALL
}


